<?php
/** LiangLeePasswdChange
 * @website Link: http://community.elgg.org/pg/profile/arsalanlee/
 * @Package Liang Lee Framework
 * @subpackage LiangLeePwdChange
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2013.
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File forgot.php
 */
?>
<?php echo elgg_echo('lianglee:password:change:info'); ?><br />

	<label><?php echo elgg_echo('loginusername'); ?></label><br />
	<?php echo elgg_view('input/text', array(
		'name' => 'user',
		'class' => 'elgg-autofocus',
		));
	?>
<?php echo elgg_view('input/captcha'); ?>
<?php echo elgg_view('input/submit', array('value' => elgg_echo('request'),'class' => "LiangLeeButton")); ?>
