<?php
/** LiangLeePasswdChange
 * @website Link: http://community.elgg.org/pg/profile/arsalanlee/
 * @Package Liang Lee Framework
 * @subpackage LiangLeePwdChange
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2013.
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File ajax_request.php
 */

require_once(dirname(dirname(dirname(__FILE__))). '/engine/start.php');

$username = get_input('user');

if (strpos($username, '@') !== false && (
    $users = get_user_by_email($username))) {
    $username = $users[0]->username;
}
$user_session = get_user_by_username($username);
if(!empty($user_session->guid)){
        $url = LiangLeeUrl::construct('resetpassword?hash='.leepwd_pwd($user_session).'&user='.$user_session->username);
        $body = elgg_echo('lianglee:password:change:body', array($url));
    if(notify_user($user_session->guid, elgg_get_config('site')->guid, elgg_echo('email:resetpassword:subject'), $body, array(), 'email')){
              echo elgg_echo("lianglee:password:change:sent");
    } 
else { 
      echo elgg_echo("lianglee:password:change:error");
     }
} 
else {
     echo 'The user is not associated with our website accounts.';
}