<?php
/** LiangLeePasswdChange
 * @website Link: http://community.elgg.org/pg/profile/arsalanlee/
 * @Package Liang Lee Framework
 * @subpackage LiangLeePwdChange
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2013.
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File start.php
 */
elgg_register_event_handler('init', 'system', 'LiangLeePwdChange');

$path = new LiangLeePath; 
include_once($path->lib('LiangLeePwdChange').'LiangLeePwdChange.php');
/**
 * LiangLeePasswordChange Settings
 *
 * @access system
 */ 
function LiangLeePwdChange() {

	elgg_register_page_handler('forgotpassword', 'lee_passwordchange_pagehandler');
	elgg_register_page_handler('resetpassword', 'lee_passwordchange_pagehandler');

}
/**
 * LiangLeePasswordChange Page Handler
 *
 * @access public
 */
function lee_passwordchange_pagehandler($page_elements, $handler) {
$page = new LiangLeePage;
$page->construct(array(
		  'handler' => $handler,
		  'page' => 'resetpassword',
		  'file' =>  lee_wwwmod . 'LiangLeePwdChange/pages/LiangLeePwdChange/change.php'
));
$page->construct(array(
		  'handler' => $handler,
		  'page' => 'forgotpassword',
		  'file' =>  lee_wwwmod . 'LiangLeePwdChange/pages/LiangLeePwdChange/forgotpassword.php'
));
}