<?php
/** LiangLeePasswdChange
 * @website Link: http://community.elgg.org/pg/profile/arsalanlee/
 * @Package Liang Lee Framework
 * @subpackage LiangLeePwdChange
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2013.
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File version.php
 */
$LiangLee_version = '1062013';
$LiangLee_release = '1.0'; 
