<?php
/** LiangLeePasswdChange
 * @website Link: http://community.elgg.org/pg/profile/arsalanlee/
 * @Package Liang Lee Framework
 * @subpackage LiangLeePwdChange
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2013.
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File change.php
 */
$content = elgg_view('LiangLeePwdChange/change', array()); 

$title = elgg_echo('lee:pwd:change');

$params = array(
	'content' => $content,
	'title' => $title,
	'sidebar' => false,
	'title' => $title,
	'filter_override' => false
);

$body = elgg_view_layout('one_sidebar', $params);

echo elgg_view_page($title, $body);