<?php
/** LiangLeePasswdChange
 * @website Link: http://community.elgg.org/pg/profile/arsalanlee/
 * @Package Liang Lee Framework
 * @subpackage LiangLeePwdChange
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2013.
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File en.php
 */
$english = array(	
	'lianglee:password:change' => "Liang Lee Change Password",
	'lianglee:password:change:forgot' => "Forgot your password?",
	'lianglee:password:change:info' => "Please Enter your email or username below:",

	'lianglee:password:change:body' => "
	Hi there,
	
	You have requested for new password please visit link below:
	
	%s
	
	",
	'lianglee:password:change:subject' => 'New password requested',
	'lianglee:password:change:sent' =>  "Please check your email.Within the email you will find a link which you must click in  order to change your account password. If the email doesn't appear shortly, please be sure to check your spam. Some anti-spam filters modify the email, so first copy any spam message to your inbox before clicking the link.",
	'lianglee:password:change:error' => "Invilid email or username please check your email or username",
	'lee:pwd:change' => "Enter new password.",
 );
					
add_translation("en", $english);
