<?php
/** LiangLeePasswdChange
 * @website Link: http://community.elgg.org/pg/profile/arsalanlee/
 * @Package Liang Lee Framework
 * @subpackage LiangLeePwdChange
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2013.
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File forgot.php
 */
echo lee_pwd_view();