<?php
/** LiangLeePasswdChange
 * @website Link: http://community.elgg.org/pg/profile/arsalanlee/
 * @Package Liang Lee Framework
 * @subpackage LiangLeePwdChange
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2013.
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File LiangLeePwdChange.php
 */

/**
 * Generate a Password
 *
 * @access admin
 */ 
function leepwd_pwd($user = ''){
if(!empty($user)){ 
         $date = date('dym');  
		 $hash = md5($username . $user->last_login . $date); 
}
 return $hash; 
}
/**
 * View form
 *
 * @access public
 */ 
function lee_pwd_view(){
lee_set_ajax_submit(array('form_id' => '#changepassword_lee', 'process_id' => '#wait'));
$ajax = elgg_view_form('LiangLeePwdChange/forgot', array(
	'action' => 'mod/LiangLeePwdChange/ajax_request.php',
	'id' => 'changepassword_lee'
));
   return $ajax;
}


